# Generated by Django 5.0.4 on 2024-04-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=9)),
                ('email_address', models.EmailField(max_length=254)),
                ('vcard_address', models.CharField(max_length=50)),
            ],
        ),
    ]
