# Generated by Django 5.0.4 on 2024-05-02 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_gen', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now=True)),
                ('topic', models.CharField(max_length=500)),
            ],
        ),
    ]
