# Generated by Django 5.0.4 on 2024-05-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_gen', '0004_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
