# Generated by Django 5.0.4 on 2024-05-04 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_gen', '0006_alter_message_date_alter_message_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
