# Generated by Django 5.0.4 on 2024-05-04 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card_gen', '0009_alter_config_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='qr_code_image',
            field=models.ImageField(null=True, upload_to='qrcodes'),
        ),
    ]
